const mongoose = require('mongoose');

// connect with local database
mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
})

// syntax to connect hosted databse
//mongoose.connect('mongodb://USERNAME:PASSWORD@HOST::PORT/DATABASE_NAME')

// Create connection
const db = mongoose.connection;
// check error condition
db.on('error', console.error.bind(console, 'Connection error'));
// open connection and finally connect
db.on('open', function () {
    console.log('connected');
})

// Create student schema with only one field Student name of type String
let StudentSchema = new mongoose.Schema({
    name: String
})

// Added a method, which return first name of the student
// Note: You can only add methods before compiling models
StudentSchema.methods.firstName = function() {
    return this.name ?
        "Student name is " + this.name :
        "Student name doesn't exist";
}

// Create & compile model
let Student = mongoose.model('Student', StudentSchema);

// Create student document
let student = new Student({name: "Ajay"})

//console.log(student) // it will console log student name with one extra field _id which is basically generated by mongodb itself

// it will console log student name with extra sentence which is added with name in method firstName
console.log(student.firstName())

// Now finally save document to database
student.save(function (err) {
    if (err)
        throw err;
    console.log('document saved')
})
